spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/${DB_NAME:bear}
    username: ${DB_USERNAME:xiongus}
    password: ${DB_PASSWORD:123456}
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 3000
  cloud:
    consul:
      host: ${CONSUL_HOST:127.0.0.1}
      port: 8500
      discovery:
        instance-id: ${spring.application.name}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true
