spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:bear}?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=false&useAffectedRows=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  redis:
    host: ${REDOS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 3000
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
