spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST:172.16.185.129}:${DB_PORT:3306}/${DB_NAME:bear}?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=false&useAffectedRows=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
  redis:
    host: ${REDOS_HOST:172.16.185.129}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 3000
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:9000

    ignore:
      urls:



  cloud:
    consul:
      host: ${CONSUL_HOST:172.16.185.129}
      port: 8500
      discovery:
        instance-id: ${spring.application.name}
    gateway:
      routes:
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/?(?<segment>.*), /$\{segment}
        - id: console-service
          uri: lb://console-service
          predicates:
            - Path=/console/**
          filters:
            - RewritePath=/console/?(?<segment>.*), /$\{segment}
        - id: market-service
          uri: lb://market-service
          predicates:
            - Path=/market/**
        - id: portal-service
          uri: lb://portal-service
          predicates:
            - Path=/portal/**