spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/${DB_NAME:bear}
    username: ${DB_USERNAME:xiongus}
    password: ${DB_PASSWORD:123456}
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 3000
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:9000
    ignore:
      urls: /**

  cloud:
    consul:
      host: ${CONSUL_HOST:127.0.0.1}
      port: 8500
      discovery:
        instance-id: ${spring.application.name}
    gateway:
      routes:
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/?(?<segment>.*), /$\{segment}
        - id: console-service
          uri: lb://console-service
          predicates:
            - Path=/console/**
          filters:
            - RewritePath=/console/?(?<segment>.*), /$\{segment}
        - id: market-service
          uri: lb://market-service
          predicates:
            - Path=/market/**
        - id: portal-service
          uri: lb://portal-service
          predicates:
            - Path=/portal/**