server:
  port: ${SERVER_PORT:8001}
  shutdown: graceful

spring:
  application:
    name: ${APP_NAME:market-service}
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 1                 # 最小连接数
      maximum-pool-size: 10           # 最大连接数
      auto-commit: false               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
    lifecycle:
      timeout-per-shutdown-phase: 30s
